name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: NuGet cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Modify jsons with secrets
        run: |
          chmod +w ./backend/AppBrowser/appsettings.json

          jq '.AllowedOrigins = [env.URL_FRONTEND] | .CarRentalBaseAPIUrl = env.URL_RENTAL' 
          ./backend/AppBrowser/appsettings.json > tmp.json && 
          mv tmp.json ./backend/AppBrowser/appsettings.json &&
          
          jq '.Jwt.Secret = env.SECRET | .Jwt.Issuer = env.URL_BROWSER | .Jwt.Audience = env.URL_BROWSER' 
          ./backend/AppBrowser/appsettings.json > tmp.json && 
          mv tmp.json ./backend/AppBrowser/appsettings.json
        env:
            URL_FRONTEND: ${{ secrets.frontendUrl }}
            URL_BROWSER: ${{ secrets.backendBrowserUrl }}
            URL_RENTAL: ${{ secrets.backendRentalUrl }}
            SECRET: ${{ secrets.backendBrowserJwtSecret }}

      - name: Build
        run: dotnet build ./backend --configuration Release

      - name: Publish
        run: dotnet publish ./backend/AppBrowser -c Release --property PublishDir=${{env.DOTNET_ROOT}}/car-rent-backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{env.DOTNET_ROOT}}/car-rent-backend"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Test
        run: dotnet test ./backend

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "CarRentalBackend"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
